<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'OneRangCatalog\Module'                        => __DIR__ . '/Module.php',
    'OneRangCatalog\Controller\OneRangCatalogController' => __DIR__ . '/src/OneRangCatalog/Controller/OneRangCatalogController.php',
    'OneRangCatalogTest\Framework\TestCase'        => __DIR__ . '/tests/OneRangCatalog/Framework/TestCase.php',
    'OneRangCatalogTest\SampleTest'                => __DIR__ . '/tests/OneRangCatalog/SampleTest.php',
);
